### ISSUE TITLE
Review translation domains are included everywhere.

### ISSUE THREAD

**Issue by aaronfc** [Automattic/gravatar-enhanced#10]
Originally reported by @jom
> @aaronfc Just happened to see this -- does it need a text domain?

In reference to https://github.com/Automattic/gravatar-enhanced/blob/trunk/src/hovercards/utils.ts#L49

Let's add the domain there, and fix any other missing translation domains.

**Comment by wellyshen** [comment]
Close this issue due to it has been fixed through [the profile block v0.2.0](https://github.com/Automattic/gravatar-enhanced/pull/9).
