### ISSUE TITLE
Make Gravatar Profile block "author" option work on site editor for single page or post

### ISSUE THREAD

**Issue by johngodley** [Automattic/gravatar-enhanced#6]
> Apparently when adding the block through the site editor into a single page or single post the "Author" option is not available.
> 
> I was expecting for it to work, but didn't test when implementing it.
> 
> Let's see how feasible it is.

From @aaronfc

**Comment by wellyshen** [comment]
Close due to this issue has been fixed through [the profile block v0.2.0](https://github.com/Automattic/gravatar-enhanced/pull/9)
